### ISSUE TITLE
CDN引入vue和vue-router引起错误

### ISSUE THREAD

**Issue by zhaorx** [hezhongfeng/vue-page-stack#1]
cdn引入的vue和vue-router,此时import 'vue-page-stack'会导致报错Cannot read property 'router' of undefined
是不是src/index.js中58-60行引起的?这里没有router实例

**Comment by hezhongfeng** [comment]
可以给个完整例子吗？

**Comment by zhaorx** [comment]
cdn引入这些
![QQ截图20190608144600](https://user-images.githubusercontent.com/13824730/59143300-50b03580-89fc-11e9-9ec8-14fd0056924e.png)
报错如下
![QQ截图20190608144751](https://user-images.githubusercontent.com/13824730/59143308-6cb3d700-89fc-11e9-894e-baccd832db83.png)
定位是`import VuePageStack from 'vue-page-stack';`这行的问题
已经定位是这里引起的,我注释掉下面代码后就ok了
![code](https://user-images.githubusercontent.com/13824730/59143350-de8c2080-89fc-11e9-9b49-ac7c2178944b.png)

**Comment by zhaorx** [comment]
能否把npm库中的代码修改下呢?

**Comment by hezhongfeng** [comment]
可以，等我回去的

**Comment by hezhongfeng** [comment]
使用最新版并配合以下使用方式，以后会试着去掉`.default`
```
Vue.use(VuePageStack.default, { router });
```

**Comment by zhaorx** [comment]
并不需要.default 加上是错的 找不到插件的install方法

**Comment by hezhongfeng** [comment]
我这有完整的例子，你把你的例子贴上来？

**Comment by zhaorx** [comment]
![image](https://user-images.githubusercontent.com/13824730/59558178-d21c4f00-901e-11e9-82e3-06c5324a2f4b.png)
![image](https://user-images.githubusercontent.com/13824730/59558181-dea0a780-901e-11e9-80a9-e4c4b6370ed4.png)
去掉default就正常了
我应该跟你贴的代码还不一样 我是vue使用CDN 但是你的stack库npm引入

**Comment by hezhongfeng** [comment]
@zhaorx 那你还真是奇怪，一个用CND另外一个用npm~那就这么用吧
