### ISSUE TITLE
在watch routes时候通过this改变数据无法让视图更新

### ISSUE THREAD

**Issue by brightstarlcg** [hezhongfeng/vue-page-stack#103]
watch: {
        $route(to, from) {
            if (from.name == 'about') {
                this.aa = '从新设置' // 不能通过this.xx改变更新视图             
            }

        }

**Comment by brightstarlcg** [comment]
<vue-page-stack>
                <router-view></router-view> // 这样不能更新视图
            </vue-page-stack>

            <keep-alive>
                <router-view></router-view> // 这样可以更新视图
            </keep-alive>

**Comment by hezhongfeng** [comment]
收到反馈，找时间处理下。

**Comment by brightstarlcg** [comment]
> 收到反馈，找时间处理下。

作者大大改了嘛 今天这个bug 没问题了

**Comment by brightstarlcg** [comment]
> 收到反馈，找时间处理下。

@hezhongfeng 作者大大 弄好了吗 今天发现这bug没问题了

**Comment by hezhongfeng** [comment]
还没弄~
