### ISSUE TITLE
Install with nuxt

### ISSUE THREAD

**Issue by nicolasreszka** [hezhongfeng/vue-page-stack#105]
Hello, we've tried to install the vue-page-stack with Nuxt. 
But going back either doesn't work (in ssr) or doesn't keep track of the scrollbar position (in static).

Is the plugin even compatible with Nuxt ?

We use Nuxt "^2.14.12". 

Here is our plugin file :

`import Vue from 'vue'
import VuePageStack from 'vue-page-stack'

export default ({ app }, inject) => {
 
    const router = app.router
    Vue.use(VuePageStack, { router })
   
}
`

Thank you very much.

**Comment by hezhongfeng** [comment]
Sorry，`vue-page-stack` don't compatible with Nuxt.

**Comment by alignwebs** [comment]
Can we have its compatiblity with NUXT please ?

**Comment by hezhongfeng** [comment]
@alignwebs 
sry, I think you can folk this rep to compatiblity with NUXT
