### ISSUE TITLE
有个问题请教下

### ISSUE THREAD

**Issue by xu-Aurora** [hezhongfeng/vue-page-stack#125]
main里面，配置Vue.use(VuePageStack, { router, name: 'canteenDetail', keyName: 'stack-key' });是不是表示就路由里面name为canteenDetail页面才会生效，其他页面都不生效？我这个逻辑是通的嘛？

**Comment by xu-Aurora** [comment]
> main里面，配置Vue.use(VuePageStack, { router, name: 'canteenDetail', keyName: 'stack-key' });是不是表示就路由里面name为canteenDetail页面才会生效，其他页面都不生效？我这个逻辑是通的嘛？

假如是通的话，我这样配置了所有的页面都是不生效的呢

**Comment by hezhongfeng** [comment]
不是，所有的页面都会生效。

这俩option在readme有说明，你也可以自己试试

**Comment by xu-Aurora** [comment]
> 不是，所有的页面都会生效。
> 
> 这俩option在readme有说明，你也可以自己试试

那有办法实现只对某个也买实现缓存，其他页面都不走缓存？

**Comment by xu-Aurora** [comment]
今天我又发现了一个bug，使用该组件后，热更新的时候页面会空白，只有点击刷新之后才正常恢复

**Comment by hezhongfeng** [comment]
> 今天我又发现了一个bug，使用该组件后，热更新的时候页面会空白，只有点击刷新之后才正常恢复

这个一直存在

**Comment by hezhongfeng** [comment]
> > 不是，所有的页面都会生效。
> > 这俩option在readme有说明，你也可以自己试试
> 
> 那有办法实现只对某个也买实现缓存，其他页面都不走缓存？

不可以，这个插件的设计初衷是实现移动端页面的缓存逻辑，和Web端不一致，所以没考虑Web的逻辑。
