### ISSUE TITLE
跳转时报错

### ISSUE THREAD

**Issue by mcuking** [hezhongfeng/vue-page-stack#13]
您好，很感谢开源这么好用的库，不过在使用过程中，路由跳转（调用 this.$router.push）引起了报错，如下图所示，另外在运行您提供的 demo  [vue-page-stack-example](https://github.com/hezhongfeng/vue-page-stack-example) 时也会报同样的错误：

![image](https://user-images.githubusercontent.com/22924912/63207981-709d5d00-c101-11e9-9232-c76586d474f3.png)

项目地址
https://github.com/mcuking/mobile-web-best-practice

demo 地址
https://mcuking.github.io/mobile-web-best-practice/

**Comment by hezhongfeng** [comment]
你的项目报错太多，跑不起来啊，另外 `vue-page-stack-example `应该是没有问题的，我在Mac下和win10下都调试过，你可以看看我的在线版本。

` vue-page-stack-example `如果确认有问题的话，可以详细说说你的环境和步骤吗？

**Comment by hezhongfeng** [comment]
我们是有在产品上使用的，一般的push肯定是没有问题的，可能在一些我们目前没遇到的情况，会和你一起解决的。

**Comment by mcuking** [comment]
同样的错误

![image](https://user-images.githubusercontent.com/22924912/63254437-5781e100-c2a6-11e9-98a2-f4c616b36eef.png)

本地 node 版本是 8.15.1

步骤：
```js
git clone ...
cd ..
npm i
npm run serve
```

另外想问下我的项目是 clone 下来安装依赖后，运行 npm run serve 报错吗？具体是报什么错呢？同样想知道下环境和步骤😂

**Comment by hezhongfeng** [comment]
确认了，确实有这个错误，等我解决吧~可能是大多数都使用的10.x.x的版本，一直没暴露出来。

**Comment by mcuking** [comment]
好的，不过我用 nvm 切换到 10.16.3 ，重新下载并运行 vue-page-stack-example 还是会有相同的报错。

![image](https://user-images.githubusercontent.com/22924912/63335616-49989280-c370-11e9-8d91-46c25bafa35f.png)

![image](https://user-images.githubusercontent.com/22924912/63336760-469ea180-c372-11e9-9b53-2569d08b5ffc.png)


另外我的项目在 node 10.16.3 运行还是没遇见报错，如果有空的话，能否截下报错的图吗？

**Comment by hezhongfeng** [comment]
问题明确了，不是node版本的问题，而是npm和yarn的问题，我这个example是带了个yarn的lock文件，使用npm后会安装最新版本的router3.1.x

**Comment by hezhongfeng** [comment]
你先正常使用吧，没什么影响，3.1.x有了一些break的改动。貌似和以前还不兼容

**Comment by hezhongfeng** [comment]
https://github.com/vuejs/vue-router/issues/2873

**Comment by mcuking** [comment]
好的，十分感谢🤣

**Comment by hezhongfeng** [comment]
上周事情比较多，这周解决

**Comment by mcuking** [comment]
好的，顺便提供下能帮到你的信息，我这里 vue-router 从 3.0.3 升级到 3.0.7 就没有报错了

![image](https://user-images.githubusercontent.com/22924912/63688839-08eebc80-c83b-11e9-83aa-bea08e55e0f6.png)

**Comment by hezhongfeng** [comment]
你还是没懂啊，3.0.x都是没问题的，只有3.1.x才会有问题，你可以看看lock文件

**Comment by mcuking** [comment]
我回退到那个 commit 后发现的确是这样的，lock 锁定到 3.1.x 了……
![image](https://user-images.githubusercontent.com/22924912/63696260-e6659f00-c84c-11e9-8336-df8bfe15b801.png)
