### ISSUE TITLE
vue3支持

### ISSUE THREAD

**Issue by zhl154381001** [hezhongfeng/vue-page-stack#137]
希望能支持一下vue3+vue-router4的使用

**Comment by hezhongfeng** [comment]
唉，不是我不支持，你看看这个[PR](https://github.com/vuejs/core/pull/4339#issuecomment-1167735001)吧，是Vue3的核心不支持，我搞不了啊

**Comment by zhl154381001** [comment]
嗯嗯，感谢您的回复


| |
heling.zhang
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2022年6月30日 08:24 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [hezhongfeng/vue-page-stack] vue3支持 (Issue #137) |

唉，不是我不支持，你看看这个PR吧，是Vue3的核心不支持，我搞不了啊

**Comment by hezhongfeng** [comment]
滴滴，支持Vue3.0了，欢迎试用
