### ISSUE TITLE
如何清空View栈

### ISSUE THREAD

**Issue by z-wade** [hezhongfeng/vue-page-stack#14]
我现在有个需求：
登录后在使用过程中某个时间点，这个账号被顶了。
那么我需要回到登录页面。
这个时候我想把所有的页面清除，然后再把登录页push出来
请问怎么做呢？
另外，
```
let UIStack = this.$pageStack.getStack();
```
我拿不到pageStack

**Comment by hezhongfeng** [comment]
1、可以提供清空的API
2、拿不到你可以看看你的版本，这个API也是别人要求后增加的

**Comment by hezhongfeng** [comment]
hello？有反馈吗

**Comment by hezhongfeng** [comment]
暂时先关闭了，如果有反馈可继续讨论。

**Comment by nadirvishun** [comment]
@hezhongfeng 目前主要是这个流程：`A(首页)->B(列表页)->C(详情页)->A(详情页提交后返回首页)`，此时在`A(首页)`再点后退，即便已经清除了`UIStack`，还是会回到`C(详情页)`。因为后退时触发的就是history里的上一页面的地址。
这种情况下有好的解决方法码？

**Comment by hezhongfeng** [comment]
@nadirvishun 这种真的是解决不了，目前js没办法控制history，所以这个记录会一直存在，我建议你可以换个角度去思考怎么解决。比如A->B->C(这里直接back两步)->A
