### ISSUE TITLE
可以支持vue3吗

### ISSUE THREAD

**Issue by ningbnii** [hezhongfeng/vue-page-stack#140]

**Comment by Murphy-Tong** [comment]
[自己实现了一个](https://github.com/Murphy-Tong/page-stack-vue3)

**Comment by hezhongfeng** [comment]
@Murphy-Tong 好的，在线demo啥的搞起来啊

**Comment by Murphy-Tong** [comment]
> @Murphy-Tong 好的，在线demo啥的搞起来啊

[done ](https://murphy-tong.github.io/ps/#/).  
https://murphy-tong.github.io/ps/#/

**Comment by hezhongfeng** [comment]
滴滴，支持Vue3.0了，欢迎试用
