### ISSUE TITLE
Throw an error Uncaught (in promise) undefined.

### ISSUE THREAD

**Issue by ezrealining** [hezhongfeng/vue-page-stack#15]
Throw an error Uncaught (in promise) undefined.
version: vue@2.6.10 + vue-router@3.0.3 + vue-page-stack@1.1.0
![error](https://user-images.githubusercontent.com/22080200/63904093-5db05400-ca42-11e9-9539-a9d802e2ed1d.png)

**Comment by hezhongfeng** [comment]
I think you used vue-router 3.1.x，3.1.x have a break change，you can check your lock file
And I've already dealt with it. Upgrade `vue-page-stack` to v1.2.0
https://github.com/vuejs/vue-router/issues/2873

**Comment by ezrealining** [comment]
So that's how it's done! 
My package-lock.json show in file vue-router@3.1.2 , thanks!
