### ISSUE TITLE
路由跳转如果直接把上一个路由的query赋值给跳转的路由会报错’parentComponent.ctx.deactivate is not a function‘

### ISSUE THREAD

**Issue by liuyinbin** [hezhongfeng/vue-page-stack#151]
跳转路由如果是
`
const route = useRoute()
const router = useRouter()
router.replace({
    path: "/home",
    query: route.query
})`
这时候就会报错 `parentComponent.ctx.deactivate is not a function`
暂时我这里的解决办法是
`let queryData = deepClone(route.query)
     delete queryData?.['stack-key']`
把这个stack-key删除后再赋值就可以，应该是如果不删除就赋值的话会导致新的页面不生产stack-key吧？

**Comment by hezhongfeng** [comment]
收到
