### ISSUE TITLE
https://hezf.online 不可访问

### ISSUE THREAD

**Issue by DevDengChao** [hezhongfeng/vue-page-stack#152]
DNS 挂了?

**Comment by hezhongfeng** [comment]
域名到期了

**Comment by hezhongfeng** [comment]
这个项目的预览地址是 ok 的

**Comment by DevDengChao** [comment]
> 域名到期了

:rofl: 

![image](https://github.com/hezhongfeng/vue-page-stack/assets/16363180/069997a0-860e-4941-b6f4-b4aa54d06b7f)

**Comment by hezhongfeng** [comment]
改一下，不是域名，是腾讯云的服务器
