### ISSUE TITLE
[bug]: 在v3.1.1版本上，页面跳转后被销毁

### ISSUE THREAD

**Issue by h-yw** [hezhongfeng/vue-page-stack#156]
描述：
node_module中版本3.1.1，Router.push 以后，页面被销毁。
vue devtool显示也是如此，组件被销毁。
更改版本号3.0.x后，表现正常

问题package.json dependencies

```json
"vue-page-stack": "^3.0.1",
```

修正package.json dependencies

```json
"vue-page-stack": "~3.0.1",
```

**Comment by hezhongfeng** [comment]
准备个例子吧，我的[这个](https://github.com/hezhongfeng/vue-page-stack-example)项目里面，没有你说的现象
