### ISSUE TITLE
从 3.0.1 升级到 3.1.2 导致的router.replace后页面缓存不生效

### ISSUE THREAD

**Issue by gaojungithub2004** [hezhongfeng/vue-page-stack#161]
从 3.0.1 升级到 3.1.2 导致的router.replace后页面缓存不生效
问题描述
1. 我replace到一个A页面
2.A页面在跳转B页面
3.B页面返回到A, A输入框数据被清空
4. 再次 从 A 跳转到B B页面返回 输入框不会被清空

**Comment by hezhongfeng** [comment]
给一个复现的小 repo 吧

**Comment by gaojungithub2004** [comment]
小 repo 怎么给啊？ 我不太会， 你给我说说，我看看， 你说的是demo？

**Comment by gaojungithub2004** [comment]
我用vite写了一个demo你可以看看
[vue-page-stack-demo.zip](https://github.com/user-attachments/files/15950540/vue-page-stack-demo.zip)

**Comment by hezhongfeng** [comment]
就是一个公开的仓库，能复现就行，最简单的就行

**Comment by hezhongfeng** [comment]
我明天看一下

**Comment by hezhongfeng** [comment]
@gaojungithub2004 已修复，需升级到最新版 3.1.3
