### ISSUE TITLE
报错：No matching export in "node_modules/vue/dist/vue.runtime.esm-bundler.js" for import "ErrorCodes"

### ISSUE THREAD

**Issue by akai-b** [hezhongfeng/vue-page-stack#163]
在添加完该包之后启动报错： No matching export in "node_modules/vue/dist/vue.runtime.esm-bundler.js" for import "ErrorCodes"

![image](https://github.com/hezhongfeng/vue-page-stack/assets/63035134/50cc7f8d-182c-4eb7-92c8-45d6bf30b27f)

"vue": "^3.3.4",
"vue-page-stack": "^3.1.3",
"vue-router": "^4.2.2"

**Comment by hezhongfeng** [comment]
你可以查看我的 example 项目

**Comment by hezhongfeng** [comment]
只贴出错误信息，我肯定查不到的

**Comment by akai-b** [comment]
> 你可以查看我的 example 项目

将vue版本升级到3.4.30解决了
但还是建议对3.4以下版本做下兼容

**Comment by hezhongfeng** [comment]
建议无效～
