### ISSUE TITLE
日志是否可以不用打印

### ISSUE THREAD

**Issue by wangqi060934** [hezhongfeng/vue-page-stack#165]
https://github.com/hezhongfeng/vue-page-stack/blob/8a0d8bd77b817388231458f43785a5d6ee15e11b/lib/main.js#L10
https://github.com/hezhongfeng/vue-page-stack/blob/8a0d8bd77b817388231458f43785a5d6ee15e11b/lib/main.js#L15

这两段日志输出是否可以去除？

**Comment by hezhongfeng** [comment]
可以，等我明天搞下

**Comment by hezhongfeng** [comment]
v3.1.5 已去除
