### ISSUE TITLE
关于切换动画

### ISSUE THREAD

**Issue by jktantan** [hezhongfeng/vue-page-stack#166]
想问一下，你这个项目是什么原因导致不能使用切换动画的？因为我自己做了一个tab的项目，tab内也是使用stack来做，是可以有切换动画的，不过我那个是自己实现了一个stack，且进退也是自己写的方法？

**Comment by hezhongfeng** [comment]
和 Transition 相关，可以看看这里
https://router.vuejs.org/zh/guide/advanced/transitions.html
