### ISSUE TITLE
某个页面刷新返回后，会报以下错误Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'shapeFlag')

### ISSUE THREAD

**Issue by lukerlv** [hezhongfeng/vue-page-stack#170]
![image](https://github.com/user-attachments/assets/04924656-81ab-446a-a558-57d6b6000aa9)

**Comment by hezhongfeng** [comment]
给个复现的最小 repo 吧

**Comment by lukerlv** [comment]
实在抱歉，没有最小repo呀，目前的项目里面的。。就发现有一个页面会有这种情况，其他页面暂时没发现，不知道什么原因

**Comment by coderchang0105** [comment]
是不是嵌套 router-view 了？

**Comment by hezhongfeng** [comment]
@lukerlv 没有就想办法搞个简单的页面复现，如果复现不了，那就找找自身问题，你们的项目我咋看。。。

**Comment by lukerlv** [comment]
@coderchang0105 没有嵌套router-view

**Comment by lukerlv** [comment]
@hezhongfeng 终于复现了
https://github.com/lukerlv/vue-page-stack-example
修改的代码如下，即可重现
![image](https://github.com/user-attachments/assets/b216906d-fa9c-4183-926e-533a8480b1d1)
