### ISSUE TITLE
如何在A页面打开A页面

### ISSUE THREAD

**Issue by Johnny-KK** [hezhongfeng/vue-page-stack#18]
测试A->B->A是可以的，A->A用push方法没有效果，麻烦问一下有支持的方法吗

**Comment by hezhongfeng** [comment]
这种情况是遵循`vue-router`的处理方式的，如果是参数的变化可以捕获到的，比如从A商品到B商品的话。你可以详细说说A->A是个什么情节下的需求吗？

**Comment by Johnny-KK** [comment]
> 这种情况是遵循`vue-router`的处理方式的，如果是参数的变化可以捕获到的，比如从A商品到B商品的话。你可以详细说说A->A是个什么情节下的需求吗？

比如说就是A商品跳转到A商品，参数是放到push里面的 this.$router.push({ name: 'good', params: params })，这种情况下页面是没有变化的

**Comment by hezhongfeng** [comment]
按照`vue-router`一样的处理就行，页面是复用的[link](https://router.vuejs.org/zh/guide/essentials/dynamic-matching.html#%E5%93%8D%E5%BA%94%E8%B7%AF%E7%94%B1%E5%8F%82%E6%95%B0%E7%9A%84%E5%8F%98%E5%8C%96)

**Comment by Johnny-KK** [comment]
> 按照`vue-router`一样的处理就行，页面是复用的[link](https://router.vuejs.org/zh/guide/essentials/dynamic-matching.html#%E5%93%8D%E5%BA%94%E8%B7%AF%E7%94%B1%E5%8F%82%E6%95%B0%E7%9A%84%E5%8F%98%E5%8C%96)

按照文档确实是可以复用组件，但是是直接改变组件内的数据，我希望是可以把当前组件直接推入栈中缓存，再打开一个新的组件重新加载，因为原来的组件可能已经有许多操作需要被缓存下来

**Comment by hezhongfeng** [comment]
好的，我会尝试增加个option来满足你说的这种情况

**Comment by Johnny-KK** [comment]
> 好的，我会尝试增加个option来满足你说的这种情况

十分感谢

**Comment by q-jason** [comment]
我在开发中也碰到了这个问题...

相同页面级组件的动态路由切换复用组件时
不触发以下：
1. 页面切换（无法做进入离开切换效果）
2. created（更多时候还是想要进一个全新的页面重新执行逻辑，用 watch 方式做监听较为奇怪= =）

场景如下：
- 产品详情 -> 产品详情（智能联想产品等）
- 新闻列表 -> 新闻列表
- ...场景还是很多的

个人想法：
这里的复用实际用处感觉并不大，创建一个全新的页面进入如何

![GIF](https://user-images.githubusercontent.com/28495915/66726423-e1e05e80-ee6b-11e9-88f5-6918f2366df5.gif)

**Comment by hezhongfeng** [comment]
@q-jason 我本身开发这个也是因为vue-navigation和其他的轮子不满足我的使用，这段时间比较忙，稍等哈。

**Comment by hezhongfeng** [comment]
同志们，这个遇到了难题，目前不知道能不能解决。

**Comment by hezhongfeng** [comment]
@Johnny-KK @q-jason 
居然找到了解决此问题的方法：
1、升级vue-page-stack到1.3.0
2、在router-view添加key值：`<router-view :key="$route.fullPath" class="router-view-c"></router-view>` 参考这次[提交](https://github.com/hezhongfeng/vue-page-stack-example/commit/db7f0dd15ba12031c6d8be63947e52983b713e73)
