### ISSUE TITLE
报错 Cannot read property 'catch' of undefined

### ISSUE THREAD

**Issue by 122687220** [hezhongfeng/vue-page-stack#19]
按照示例集成到自己的项目中，工程跑起来后，只要this.$router.push({ name: 'home-page' }) 就会报 Cannot read property 'catch' of undefined
![WX20190924-083800](https://user-images.githubusercontent.com/35905503/65472585-bd194c80-dea6-11e9-9e9c-445a75dbf571.png)

**Comment by 122687220** [comment]
![WX20190924-091149](https://user-images.githubusercontent.com/35905503/65474774-a0354700-deaf-11e9-8bf5-bedeaeddc162.png)
![WeChat2658053fdce4655bbb85183f53eded7d](https://user-images.githubusercontent.com/35905503/65474837-d96db700-deaf-11e9-8b52-c4dd9d5d1d57.png)
所有路由都是通过router文件夹下面的index.js进行自动加载
vue-page-stack  v1.2.1和v1.2.2都有这个问题

**Comment by hezhongfeng** [comment]
`vue-router`的版本是多少？是不是没有升级到最新版？我的1.2.x针对最新版做了处理

**Comment by 122687220** [comment]
vue-router 3.0.7

**Comment by 122687220** [comment]
vue-router 更新到最新版 v3.1.3 问题解决了
