### ISSUE TITLE
npm安装后无法使用

### ISSUE THREAD

**Issue by hhhh20** [hezhongfeng/vue-page-stack#2]
按照说明配置以后，无法使用
![image](https://user-images.githubusercontent.com/53212031/61692769-d136b580-ad60-11e9-8aa8-f95f27999bfe.png)

**Comment by hezhongfeng** [comment]
请提供demo

**Comment by hezhongfeng** [comment]
而且看提示信息应该是你的nextTick中的错误

**Comment by hhhh20** [comment]
------------------ 原始邮件 ------------------
发件人: "hezf"<notifications@github.com>;
发送时间: 2019年7月23日(星期二) 下午3:46
收件人: "hezhongfeng/vue-page-stack"<vue-page-stack@noreply.github.com>;
抄送: "忘记了"<1017861208@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [hezhongfeng/vue-page-stack] npm安装后无法使用 (#2)




请提供demo

**Comment by hezhongfeng** [comment]
？

**Comment by hhhh20** [comment]
发送了demo

**Comment by hhhh20** [comment]
[demo.zip](https://github.com/hezhongfeng/vue-page-stack/files/3421080/demo.zip)

**Comment by hezhongfeng** [comment]
如果你对Vue和vue-router还不知道怎么使用的话，我建议你使用@vue/cli去生成项目。
你这里的问题是由于你自己的路由设置有问题, App.vue是整个项目的根，不能在放在路由里了，路由是放在App里面的
```
import Vue from 'vue'
import Router from 'vue-router'

// 登录
const Login = () => import('@/views/Login.vue')

Vue.use(Router)

export default new Router({
  routes: [
    {
      path: '/',
      component: Login
    }
  ]
})
```
