### ISSUE TITLE
路由嵌套的问题

### ISSUE THREAD

**Issue by kailong321200875** [hezhongfeng/vue-page-stack#20]
用了这个插件，发现在路由嵌套的时候是有问题的，<vue-page-stack>包裹在第二层的 router-view ，这一层路由的视图跳转的时候没办法显示。

**Comment by hezhongfeng** [comment]
你好，这个插件主要是在移动端SPA使用的，你们移动端也嵌套了吗？

**Comment by kailong321200875** [comment]
> 你好，这个插件主要是在移动端SPA使用的，你们移动端也嵌套了吗？

目前是有嵌套的存在，所以看下你那边是否有提供解决颁发

**Comment by hezhongfeng** [comment]
我不准备解决：
1、是觉得很少会用到嵌套路由的情况
2、是我感觉不好解决
你可以把你的真实需求描述下，我看看能不能在现有条件下给你参谋下

**Comment by kailong321200875** [comment]
> 我不准备解决：
> 1、是觉得很少会用到嵌套路由的情况
> 2、是我感觉不好解决
> 你可以把你的真实需求描述下，我看看能不能在现有条件下给你参谋下

那没事，我换成动态组件
