### ISSUE TITLE
新示例，新功能 clearPush/backReplace，新方法 setStack/clearStack

### ISSUE THREAD

**Issue by violetice** [hezhongfeng/vue-page-stack#22]
https://gitee.com/hezf/vue-page-stack/pulls/1

**Comment by hezhongfeng** [comment]
你先说说添加这些API的用意吧，可以详细描述下使用场景

**Comment by violetice** [comment]
都是为了更好的模拟App，截获物理返回键有我自定义的返回方式。
clearPush：清除所有页面栈，跳转新页面。没有前面的页面栈怎么返回都没用。适用于返回首页，退出。
backReplace：清除指定页面后的页面栈，重定向到指定页面。适用于返回文章列表。

更高级的用法可以通过 setStack/clearStack 手动实现。

**Comment by violetice** [comment]
backReplace：重定向到页面栈中的指定页面

**Comment by hezhongfeng** [comment]
1 、clearPush这个是不是可以通过操作页面栈然后push
2、backReplace这个不可以通过go完成吗？

**Comment by violetice** [comment]
我写好了，你看一下在gitee。可能多层路由上面还有点问题
https://gitee.com/hezf/vue-page-stack/pulls/1

**Comment by hezhongfeng** [comment]
我知道你写好了，我也看了你增加的东西，如果可以通过组合的方式完成，为什么要增加这些API?
