### ISSUE TITLE
请问同级页面跳转如何处理动画？

### ISSUE THREAD

**Issue by imRz1015** [hezhongfeng/vue-page-stack#23]
目前跳转时params里总会带有forward或者back，可是同级页面跳转我想要直接切换而非带上前进动画或者后退动画，请问如何实现呢？

**Comment by imRz1015** [comment]
> 目前跳转时params里总会带有forward或者back，可是同级页面跳转我想要直接切换而非带上前进动画或者后退动画，请问如何实现呢？

使用replace替换时，params里面同样也是带上的forward

**Comment by hezhongfeng** [comment]
什么是同级？是商品A到商品B吗？
这样的话你可以自己监控路由的变化，取消掉动画
