### ISSUE TITLE
Cannot read property 'catch' of undefined

### ISSUE THREAD

**Issue by HHL030303** [hezhongfeng/vue-page-stack#24]
引入vue-page-stack  如题主所示引入，报上述错误
$router.push 到文章页报错

**Comment by hezhongfeng** [comment]
#19

**Comment by HHL030303** [comment]
更新了router到最新版本  删除掉之前安装的所有包  还是会有这个问题

**Comment by hezhongfeng** [comment]
你自己检查一下，你肯定是没有更新。

**Comment by HHL030303** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"hezf"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月29日(星期二) 上午10:30
收件人:&nbsp;"hezhongfeng/vue-page-stack"<vue-page-stack@noreply.github.com&gt;;
抄送:&nbsp;"710682162"<710682162@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [hezhongfeng/vue-page-stack] Cannot read property 'catch' of undefined (#24)




你自己检查一下，你肯定是没有更新。

**Comment by hezhongfeng** [comment]
#13 
查看node_modules文件夹才能确定你是否更新，最新版是针对最新的router做了处理的，提issue之前先看看是否有人提过了。
