### ISSUE TITLE
每进一个路由导航触发了两次

### ISSUE THREAD

**Issue by yellowbeee** [hezhongfeng/vue-page-stack#25]
`
router.beforeEach(async (to, from, next) => {
   //这里触发了两次
})
`

**Comment by hezhongfeng** [comment]
你好，你可以看看我这个插件的源码，我确实是对beforeEach进行了拦截处理，不算是bug。
 https://github.com/hezhongfeng/vue-page-stack/blob/23b028ca411c07a44f5acdde9067ecd47a797c1b/src/index.js#L31

**Comment by yellowbeee** [comment]
你好，假如我使用 `this.$router.push('/a')` 跳转到 a 页面，会分别进入我自定义的beforeEach和源码中拦截的beforeEach，然后我发现源码中会在跳转路由基础上添加 `params`参数，这会导致自定义的beforeEach 又再次触发一次

目前我临时的处理方法是将源码中拦截的beforeEach的执行顺序提前到自定义的beforeEach之前
```
router.beforeHooks.reverse()
```

**Comment by hezhongfeng** [comment]
可以提PR哈

**Comment by hezhongfeng** [comment]
最新版已经发布了，1.4.2
