### ISSUE TITLE
$router.go(-1)，可以通知上级页面重新渲染吗？

### ISSUE THREAD

**Issue by LaoBnan** [hezhongfeng/vue-page-stack#37]
举例：确认订单页>选择收货地址>执行$router.go(-1)返回到确认订单页
此时希望确认订单页能重新渲染，又不记录选择收货地址的历史记录

**Comment by hezhongfeng** [comment]
没看懂你第二行的描述，为什么要重新渲染？
1、选择收货地址页更新选择的收货地址，可以通过vuex完成
2、返回确认订单页后vuex中的地址自然更新了
