### ISSUE TITLE
App.vue使用动画，整个页面导航也会伴随动画。

### ISSUE THREAD

**Issue by jianhao2010303** [hezhongfeng/vue-page-stack#39]
<transition :name="transitionName">
      <vue-page-stack>
        <router-view :key="$route.fullPath" class="router-view-c"></router-view>
      </vue-page-stack>
    </transition>

在子组件Home 中， <router-view></router-view> 子组件（底部导航），整个页面都会有动画。
请问怎么解决？

**Comment by hezhongfeng** [comment]
没看懂你的问题

**Comment by jianhao2010303** [comment]
你的demo中，在首页有两个菜单，首页和关于，首页和关于相互切换时，下侧菜单也会随之变化。
有没有类似其他app 一样，下面导航切换没有动画，只有点击某一个详情时，才有动画。

**Comment by hezhongfeng** [comment]
感谢反馈，原因是Home的首页和关于的路由不同，会马上解决这个问题。

**Comment by jianhao2010303** [comment]
多谢。修改好了可以马上试一试。这个问题头疼好久了。

**Comment by hezhongfeng** [comment]
这个其实非常容易解决，不属于vue-page-stack的问题，vue-page-stack只在路由变化的时候才会存储UI栈，这里在home的tab切换会改变路由，不变路由就好了。
https://github.com/hezhongfeng/vue-page-stack-example/commit/9b75b8ed8d28bb5d98b2652883e06de3bf0f5f96
