### ISSUE TITLE
路由切换有BUG

### ISSUE THREAD

**Issue by jianhao2010303** [hezhongfeng/vue-page-stack#41]
没办法截图。来回切换home与关于，两页面内容会重叠。

**Comment by hezhongfeng** [comment]
chrome问题

**Comment by jianhao2010303** [comment]
真机上ok的？

**Comment by hezhongfeng** [comment]
是的，你可以在多个环境下自己测试下。在Chrome下模拟出问题也是最新的更新才出现的

**Comment by jianhao2010303** [comment]
ok。我试一试。

**Comment by jianhao2010303** [comment]
我看你是用tabs 实现的下侧菜单。有单用 我们这个组件 实现的 菜单切换例子吗。 类似只有一个router-view，所有切换都是路由变化的。

**Comment by hezhongfeng** [comment]
没看懂你的问题

**Comment by jianhao2010303** [comment]
1.我们现在的demo 是： <cube-tab-panels > ,对应下侧带单是 tabs的切换。
2. 我们之前的项目都是，Home.vue中， 含有2部分： 一部分是 子路由，router-view, 另一部分是下侧菜单，当点击菜单变化时都是子路由变化，当点击某一个详情时，是APP.vue 中的路由变化。

所以想问： 有没有父子路由搭配应用的demo？

**Comment by hezhongfeng** [comment]
1、这个插件不支持子路由的方式另外
2、我个人建议在移动端的Home下很没有必要使用嵌套路由，使用tab是比较合理的选择。

**Comment by jianhao2010303** [comment]
如果首页内容比较丰富，包括视频和轮播，只是切换tab会比较影响性能吧？

**Comment by hezhongfeng** [comment]
性能不好就优化性能，可以对比微信的下方tab，UI栈是一直存在的。
