### ISSUE TITLE
每次将tab切回来都会重新创建一个页面

### ISSUE THREAD

**Issue by lawDavid** [hezhongfeng/vue-page-stack#42]
我的主页面下面有四个tab，每次点击tab按钮都是通过this.$router.push(/xxx);进行页面跳转。
用了这个组件之后每次切换前一个页面都不会destroy，但是每次切回来这个页面又会重新create一遍，来回切换会生成很多无用的页面。
帮我看看是我用错了还是组件有问题？
![63BC6076-FE05-4624-B422-269D51A9BD36](https://user-images.githubusercontent.com/14157364/70982454-f5b97280-20f1-11ea-992d-3bbfb69200dd.png)
![CF6D7692-DB8C-4A38-BF73-CA09AF203892](https://user-images.githubusercontent.com/14157364/70982458-f7833600-20f1-11ea-8ffe-0f82f86fb5c7.png)
![B0C28CA0-AEE1-4CB0-A172-8B6A488B7E46](https://user-images.githubusercontent.com/14157364/70982486-04a02500-20f2-11ea-91e8-342bab3e3aac.png)

**Comment by hezhongfeng** [comment]
https://github.com/hezhongfeng/vue-page-stack/issues/39
