### ISSUE TITLE
pc网页能用吗

### ISSUE THREAD

**Issue by Aarthas** [hezhongfeng/vue-page-stack#43]
pc网页能用吗

**Comment by hezhongfeng** [comment]
你能详细说说你的需求吗？感觉PC端用不上啊

**Comment by Aarthas** [comment]
pc端网页，比如：网页的左边是固定的（menu），右边是显示区域，在该区域内，显示商品列表，点击某个item，跳转到商品详情，该区域左上角给显示个返回按钮，点击返回到商品列表。左边menu区域始终不变。

**Comment by hezhongfeng** [comment]
感觉不需要我这个，我这个还是适合在移动端使用，PC端的交互和移动端还是差很多的。
