### ISSUE TITLE
跳转时，没有传入path，只想改变路由的query参数，报错。

### ISSUE THREAD

**Issue by rayxiehui** [hezhongfeng/vue-page-stack#46]
看了报错，发现path必须， 有什么方法可以捕捉或者优化吗？

**Comment by hezhongfeng** [comment]
不使用path，你是想使用什么？

**Comment by pfpGit** [comment]
replace异常捕获有问题

**Comment by hezhongfeng** [comment]
@pfpGit 老哥，建议单独开个issue，请详细描述下

**Comment by hezhongfeng** [comment]
你好，有反馈吗？

**Comment by rayxiehui** [comment]
因为页面带有路由参数，在改变页面的选项时，只想同时改变路由参数，而path不变，用的是replace， 报错。

**Comment by rayxiehui** [comment]
还遇到过一个问题， 在页面中使用了websocket，结果导致页面的函数被激活，有什么方法可以避免吗

**Comment by hezhongfeng** [comment]
1、能给我展示相关代码或者最小仓库吗？
2、websocket的问题我也没懂什么意思

**Comment by rayxiehui** [comment]
1.  <code>
this.$route.replace({
  query: {   cityId: '321111'}
})
</code>

2.  
页面理论上时没有缓存的，但里面但函数被websocket 触发了。如果时缓存但组件，里面函数应该是没有在内存中。

**Comment by rayxiehui** [comment]
发现一个问题， 我页面混入minxin，前后页面都有，回退后，是上个页面但mixin方法，本页面没有调用

**Comment by hezhongfeng** [comment]
涉及path的问题已经明确回答，其它问题建议单独开issue，描述难度较大的建议新建个临时仓库展示。
