### ISSUE TITLE
1.能否关闭指定的页面？2.能否关闭所有页面，打开到应用内的某个页面？

### ISSUE THREAD

**Issue by shuweitao** [hezhongfeng/vue-page-stack#48]
1.能否关闭指定的页面？2.能否关闭所有页面，打开到应用内的某个页面？

**Comment by hezhongfeng** [comment]
可以仔细描述下需求吗？我没看懂你想做什么，你想自己手动控制Stack?

**Comment by DuShuYuan** [comment]
微信中打开-授权页面-登录页面-首页
他的意思应该是  到首页时  从堆栈中移除授权和登录页面，让首页变成堆栈底

**Comment by DuShuYuan** [comment]
或者是 不缓存 授权页面和登录页面

**Comment by hezhongfeng** [comment]
针对你的问题『从堆栈中移除授权和登录页面，让首页变成堆栈底』，你可以通过`this.$pageStack.getStack()`获取栈，可以手动操作，这些都在说明中有写。其他的问题建议新开issue单独讨论和处理
