### ISSUE TITLE
能否强制缓存某个页面？

### ISSUE THREAD

**Issue by midoushitongtong** [hezhongfeng/vue-page-stack#49]
##### 使用场景: 移动端底部 tab 导航
底部 tab 导航不管是 `push` 或者是 `replace` 操作, 页面都应该被缓存下来

**Comment by hezhongfeng** [comment]
类似于微信的那种吧？
这样的话我建议，不要push或者replace，就是不改变路由。
首页就是首页，切换tab只是显示的内容不同，不需要切换路由。

**Comment by midoushitongtong** [comment]
> 类似于微信的那种吧？
> 这样的话我建议，不要push或者replace，就是不改变路由。
> 首页就是首页，切换tab只是显示的内容不同，不需要切换路由。

ok, 感谢你的建议
