### ISSUE TITLE
带动画转场的,返回滚动条无法定位

### ISSUE THREAD

**Issue by lsxm** [hezhongfeng/vue-page-stack#50]
![image](https://user-images.githubusercontent.com/12426873/80201384-a31b3480-8656-11ea-9290-8bfaf6b6ce74.png)
带动画的话,返回后位置无法定位到之前的地方,都是在最上面,如果去掉transition的话是可以记住位置的

**Comment by lsxm** [comment]
找到问题了,是你那个demo写的有问题,去掉.router-view-c里的position: absolute;就可以了

**Comment by lsxm** [comment]
但是,不加.router-view-c里的position: absolute;页面切换时又会变形

**Comment by hezhongfeng** [comment]
我在ios 手机上测试了我的demo，是没问题的

**Comment by hezhongfeng** [comment]
我们的正式应用（IOS，安卓，微信公众号）上面也是没问题的，是否可以提供更多的反馈信息？

**Comment by lsxm** [comment]
认真对比一下,原来是我的#app没有设置position: relative;导致不能记住滚动条位置.已经可以了,多谢

**Comment by lsxm** [comment]
> 我们的正式应用（IOS，安卓，微信公众号）上面也是没问题的，是否可以提供更多的反馈信息？

请教一下,返回后保持滚动条位置不变的代码在哪里,我找不到,多谢

**Comment by hezhongfeng** [comment]
『返回后保持滚动条位置不变的代码』?
源码就是啊，保存的是vnode

**Comment by hezhongfeng** [comment]
此问题已结束，关闭
