### ISSUE TITLE
可以隐藏地址栏的stack-key吗

### ISSUE THREAD

**Issue by a365344743s** [hezhongfeng/vue-page-stack#51]
我们是直播业务，地址类似下面这样
http://localhost:8080/#/livePlay/886688?stack-key=428bfa92
我想隐藏?stack-key=428bfa92这一段，因为用户可以将这个地址分享出去，但是stack-key参数很奇怪

**Comment by hezhongfeng** [comment]
隐藏不了，没有这个stack-key，无法准确的判断back还是forward
