### ISSUE TITLE
自定义stack-key-dir

### ISSUE THREAD

**Issue by a365344743s** [hezhongfeng/vue-page-stack#52]
可以增加支持外部传入stack-key-dir来控制动画吗，
我现在index.js中修改的，
![image](https://user-images.githubusercontent.com/15245246/81389092-dc21d180-914b-11ea-9884-70e10b37de86.png)

**Comment by hezhongfeng** [comment]
你可以详细说说你的需求和使用场景吗？

**Comment by a365344743s** [comment]
我们是直播业务，直播房间的url需要单独存在，可以单独分享这个url出去打开，直播房间一直有返回按钮。如果是单独打开的直播房间url，点返回是没有堆栈的。所以我们在直播房间点返回时判断了堆栈长度如果大于1则正常back，否则使用replace跳到首页。但是使用replace，动画一直是forward，我们希望这种情况动画也是back动画。

**Comment by hezhongfeng** [comment]
back动画和forward动画是你自己定义的
1、可以判断当前的页面是分享的
2、可以在用户点击back的时候（实际是replace）的时候使用back的动画
