### ISSUE TITLE
首页tab切换问题

### ISSUE THREAD

**Issue by DuShuYuan** [hezhongfeng/vue-page-stack#54]
首页有多个tab，来回切换时，tab页每次都是新的
路由：

  {
    name: "foot",
    path: "/foot",
    meta: { title: "底部导航" },
    component: () => import("@/views/main/foot.vue"),
    children: [
      {
        name: "home",
        path: "/home",
        meta: { title: "首页" },
        component: () => import("@/views/main/home.vue")
      },
      {
        name: "projectInfo",
        path: "/projectInfo",
        meta: { title: "项目信息" },
        component: () => import("@/views/main/projectInfo.vue")
      },
      {
        name: "workPlan",
        path: "/workPlan",
        meta: { title: "工作计划" },
        component: () => import("@/views/main/workPlan.vue")
      },
      {
        name: "task",
        path: "/task",
        meta: { title: "员工任务" },
        component: () => import("@/views/main/task.vue")
      },
      {
        name: "personal",
        path: "/personal",
        meta: { title: "我的" },
        component: () => import("@/views/main/personal.vue")
      }
    ]
  }

页面：

    <router-view />
    <van-tabbar v-model="active">
      <van-tabbar-item to="/projectInfo">
        <span>项目信息</span>
      </van-tabbar-item>
      <van-tabbar-item to="/workPlan">
        <span>工作计划</span>
      </van-tabbar-item>
      <van-tabbar-item to="/home">
        <span>首页</span>
      </van-tabbar-item>
      <van-tabbar-item to="/task">
        <span>员工任务</span>
      </van-tabbar-item>
      <van-tabbar-item to="/personal">
        <span>我的</span>
      </van-tabbar-item>
    </van-tabbar>

如果router-view 用vue-page-stack 包起来就什么都不显示了，白屏

**Comment by DuShuYuan** [comment]
还有页面返回时，tab中的滚动条总是会置顶

**Comment by hezhongfeng** [comment]
提供个复现的建议仓库吧

**Comment by DuShuYuan** [comment]
> 提供个复现的简易仓库吧

https://github.com/DuShuYuan/vueApp

**Comment by hezhongfeng** [comment]
看了你提供的rep，建议你看下这个，https://github.com/hezhongfeng/vue-page-stack/issues/49

**Comment by DuShuYuan** [comment]
我更新了代码，使用子组件的方式切换tab，但是返回首页时滚动位置还总是置顶

**Comment by hezhongfeng** [comment]
可以参考 https://github.com/hezhongfeng/vue-page-stack/issues/36

**Comment by DuShuYuan** [comment]
没看明白。。。。
试了改为全局滚动就不会置顶了，但这样并不符合设计要求，顶部标题栏和底部tab栏要固定的

**Comment by hezhongfeng** [comment]
你反应的问题已经不是我这个插件能够解决的问题了~

**Comment by coderchang0105** [comment]
> 没看明白。。。。 试了改为全局滚动就不会置顶了，但这样并不符合设计要求，顶部标题栏和底部tab栏要固定的

可以参照 https://github.com/zack24q/vue-navigation/issues/43，自己封装个滚动组件记住位置
