### ISSUE TITLE
this.$pageStack.getStack() 栈里的信息为什么不包含路由信息，比如路由的name

### ISSUE THREAD

**Issue by renaiqin** [hezhongfeng/vue-page-stack#59]
这个栈里信息基本都没有返回路由的信息，那这样 这个栈的用处是什么呢

**Comment by hezhongfeng** [comment]
绝大多数的时候，是不需要操作Stack的，只有少数情况下才需要用到这个API，可以查看下这个https://github.com/hezhongfeng/vue-page-stack/issues/14
我们这的业务上没用过这个API

**Comment by renaiqin** [comment]
> 最初的时候，是不需要操作Stack的，只有少数情况下才需要用到这个API，可以查看下这个[＃14](https://github.com/hezhongfeng/vue-page-stack/issues/14)
> 我们这的业务上没用过这个API

**Comment by renaiqin** [comment]
因为这个栈是跳转路由的栈，那你们那边可以返回一下路由的信息吗，因为我这边的业务是封装vue的跳转路由，就是把go,push,replace封装一下，调用的地方只需要传一个name,和query。go跳转的时候封装的组件里用push代替，这样的话我就需要维护路由栈，刚好你的这个$ pageStack.getStack就是这个栈，但是里面没有路由信息，不知道你那边有什么好的方法解决这个问题

**Comment by hezhongfeng** [comment]
你想自己封装的话，不需要使用我这个插件~
你的需求我没搞懂，不过我建议你不要自己维护路由栈，坑很多，你可以试试folk本项目试试有了路由的信息是否可以完成你的需求

**Comment by renaiqin** [comment]
$ pageStack.getStack 这个栈不是页面跳转的栈吗，比如a,b,c,d四个页面，a跳转到b,b跳转到c,c跳转到d，d在跳转到a,a在跳转到其他页面，等等，反正就是页面的各种跳转，那这个栈是保存a跳转到b的路由信息，b跳转到c的路由信息的吗？

**Comment by hezhongfeng** [comment]
插件不保存路由信息~路由是浏览器保存的

**Comment by renaiqin** [comment]
mixin(router);
  router.beforeEach((to, from, next) => {
    if (!hasKey(to.query, keyName)) {
      if (hasSameMatched(to, from)) {
        to.query[keyName] = from.query[keyName];
      } else {
        to.query[keyName] = getKey("xxxxxxxx");
      }
      let replace =
        history.action === config.replaceName || !hasKey(from.query, keyName);
      next({
        hash: to.hash,
        path: to.path,
        name: to.name,
        params: to.params,
        query: to.query,
        meta: to.meta,
        replace: replace,
      });
    } else {
      let index = getIndexByKey(to.query[keyName]);
      if (index === -1) {
        to.params[keyName + "-dir"] = config.forwardName;
      } else {
        to.params[keyName + "-dir"] = config.backName;
      }
      next({
        params: to.params
      });
    }
  });


这段代码里to.query[keyName] = getKey("xxxxxxxx"); 我把getKey("xxxxxxxx") 换成from.name 那么在pageStack.getStack里是不是就会有路由的name了

**Comment by renaiqin** [comment]
或者我加一个参数  to.query[routeName] = from.name; 这个栈的数组是不是就会返回路由的name了呢？望指教


mixin(router);
  router.beforeEach((to, from, next) => {
    if (!hasKey(to.query, keyName)) {
      if (hasSameMatched(to, from)) {
        to.query[keyName] = from.query[keyName];
      } else {
        to.query[keyName] = getKey("xxxxxxxx");
      }
       ### to.query[routeName] = from.name;###
      let replace = history.action === config.replaceName || !hasKey(from.query, keyName);
      next({
        hash: to.hash,
        path: to.path,
        name: to.name,
        params: to.params,
        query: to.query,
        meta: to.meta,
        replace: replace,
      });

**Comment by hezhongfeng** [comment]
这个真回答不了你
