### ISSUE TITLE
使用插件，有办法做到选项卡页面跳转达到缓存的效果吗？

### ISSUE THREAD

**Issue by youhangbiao** [hezhongfeng/vue-page-stack#61]

**Comment by hezhongfeng** [comment]
没懂你是什么应用场景

**Comment by youhangbiao** [comment]
场景：A页面跳转B页面，B页面跳转C页面，这时候路由记录有三个。我再使用push跳转至B页面，这时候我携带路由记录B页面的key值，从缓存中获取打开的B页面，但是路由记录中的C却释放了，导致我跳转C页面是重新加载。有办法解决这一问题吗？还是说我写的方式有问题。

**Comment by youhangbiao** [comment]
上面写错了 ，不是重定向，就是简单的跳转C页面

**Comment by hezhongfeng** [comment]
留一个issue，先仔细看文档和在线Demo

**Comment by hezhongfeng** [comment]
你好，还有问题吗？请编辑你的描述内容

**Comment by youhangbiao** [comment]
问题还是上午的问题，可能是我没看清文档。谢谢了

**Comment by hezhongfeng** [comment]
好的，可以参考我的demo源码，里面很清楚。
