### ISSUE TITLE
是否缓存页面路由可配置

### ISSUE THREAD

**Issue by huqio** [hezhongfeng/vue-page-stack#63]
有些页面不需要缓存，为了少占用内存

**Comment by hezhongfeng** [comment]
你好，没有相关的option：
1、我本身不推荐这么做，stack的层数一般会很少
2、非想要这么做的话，可以在全局的路由守卫手动管理stack

**Comment by hezhongfeng** [comment]
你好，有反馈吗？

**Comment by hezhongfeng** [comment]
如果这周没有反馈，此issue将会被关闭
