### ISSUE TITLE
可以给某些页面选择不配置stack-key吗

### ISSUE THREAD

**Issue by DallenCat** [hezhongfeng/vue-page-stack#65]
遇到公众号ios分享的问题，从页面Alocation.href跳转了页面B，但是页面B带了stack-key，导致签名不成功。用户可以自主选择给页面B不配置stack-key吗？

**Comment by hezhongfeng** [comment]
可以再详细描述下吗？我没搞懂

**Comment by DallenCat** [comment]
微信公众号H5的签名机制需要一个实时的URL，IOS单页面应用的URL与安卓的不同，安卓是每个页面的URL都是“域名+路由”，IOS是因为只有一个index.html存在，所以访问的实际上永远是同一个页面。用vue的router跳转是获取不到最新的url的，所以我用了href跳转，但是跳转的路径我只写了“www.xxxxx/B”，我拿去签名的url也是“www.xxxxx/B”，但是实际上当我跳转到B页面时，路径上带上了stack-key参数，“www.xxxxx/B”与“www.xxxxx/B?stack-key=xxxx”微信不认可他们是同一个url，这就导致了我无法在B页面签名成功，只能在B页面再刷新一次页面保存带stack-key的url，但是这样的用户体验不是特别好

**Comment by hezhongfeng** [comment]
还是没搞懂你在描述的是什么，我们可以获取到实时的URL，我们的公众号获取签名和timestamp是很正常的，也不存在IOS和安卓不同的情况。

**Comment by DallenCat** [comment]
有用过公众号分享的签名吗？不是微信支付的

**Comment by hezhongfeng** [comment]
分享、支付、扫码、等位等我这用的是同一个，申请一次签名后一直用这一个，不会重复申请。

**Comment by DallenCat** [comment]
是在App.vue里就调用了吗？

**Comment by hezhongfeng** [comment]
在App.vue里就调用了，然后就一直使用这一套签名。

**Comment by hezhongfeng** [comment]
你好，没其他事情的话，这个issue就可以close了
