### ISSUE TITLE
TypeError: Cannot read property 'catch' of undefined     at VueRouter.router.push (vue-page-stack.common.js:1619)

### ISSUE THREAD

**Issue by itlihuaxin** [hezhongfeng/vue-page-stack#66]
TypeError: Cannot read property 'catch' of undefined
    at VueRouter.router.push (vue-page-stack.common.js:1619)

**Comment by hezhongfeng** [comment]
what's the version of vue-router?

**Comment by itlihuaxin** [comment]
"vue-router": "3.0.6"

**Comment by itlihuaxin** [comment]
this.$router.go(-1) 这个还在原页面不动，虽然地址栏变化了

**Comment by itlihuaxin** [comment]
this.$router.go(-1) 这个还在原页面不动，虽然地址栏变化了，然后导致所有的路由都失效了，卡死在当前页面

**Comment by hezhongfeng** [comment]
需要升级到最新版

**Comment by itlihuaxin** [comment]
"vue-router": "^3.3.4"一样有这个问题啊
