### ISSUE TITLE
this.$router.go(-1) 这个还在原页面不动，虽然地址栏变化了，然后导致所有的路由都失效了，卡死在当前页面

### ISSUE THREAD

**Issue by itlihuaxin** [hezhongfeng/vue-page-stack#67]
this.$router.go(-1) 这个还在原页面不动，虽然地址栏变化了，然后导致所有的路由都失效了，卡死在当前页面

"vue-router": "^3.3.4"

**Comment by hezhongfeng** [comment]
1、和我的例子仔细对比下，哪里不一样，也请查看过往的issue，不要一有问题就开issue。
2、最后还有疑问的话，可以开一个仓库复现这个问题，我会跟踪处理
