### ISSUE TITLE
vue-page-stack：Clear all page cache

### ISSUE THREAD

**Issue by zhaxie** [hezhongfeng/vue-page-stack#68]
Hello, can you provide a method to clear all the router cache. 
Because  I want to router back to root page (the home page) but It existed the cached page stacks that I unwated.   
So，this methods is usefully.

eg:  this.$pageStack.cleanRoutes();

**Comment by hezhongfeng** [comment]
You can use https://github.com/hezhongfeng/vue-page-stack#get-current-ui-stack to operate UI Stack anyway.

**Comment by zhaxie** [comment]
Thanks




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "hezf"<notifications@github.com&gt;; 
发送时间: 2020年8月14日(星期五) 下午4:55
收件人: "hezhongfeng/vue-page-stack"<vue-page-stack@noreply.github.com&gt;; 
抄送: "з"<787631162@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [hezhongfeng/vue-page-stack] vue-page-stack：Clear all page cache (#68)





 
You can use https://github.com/hezhongfeng/vue-page-stack#get-current-ui-stack to operate UI Stack anyway.
