### ISSUE TITLE
控制台报这个错

### ISSUE THREAD

**Issue by qaz4890303** [hezhongfeng/vue-page-stack#69]
Error in render: "TypeError: Cannot read property 'vnode' of undefined"

**Comment by hezhongfeng** [comment]
1、可以对比下，样例仓库
2、还有问题的话，需要提供个在线的复现仓库

**Comment by qaz4890303** [comment]
抱歉  因为我在app.vue 中用    this.$router.replace 自动跳转  才会出现这个问题。

**Comment by hezhongfeng** [comment]
来个复现仓库吧，你这一句话我确实找不到问题的原因，如果你自己解决了，可以关闭这个issue。

**Comment by qaz4890303** [comment]
app.vue 页面显示部分代码   把下面的 this.$router.replace 改成this.$router.push就不会出现问题了    

created(){
      //挂载方法供app调用
       window.getTrafficCard = this.getTrafficCard;
   
    },
    methods:{
     
      //原生app传递用户信息调用
      getTrafficCard(res) {
              if(data.length===2){             
                this.$router.replace({
                  name:"Home",
                  params:{
                    routerType:"push"
                  }
                })
              }else if(data.length===3){
                 this.$router.replace({
                  name:"Details",
                  params:{
                     routerType:"push",
                     gatewayId:data[1]
                  }
                })
              }
   
            }
          }
