### ISSUE TITLE
关于cube-scroll的问题

### ISSUE THREAD

**Issue by xupd** [hezhongfeng/vue-page-stack#70]
如果不使用cube-scroll这个组件，是不是就无法保持记录滚动，我看之前issues有提到这个问题，但是看得不太明白。

**Comment by hezhongfeng** [comment]
不是

**Comment by xupd** [comment]
请问有什么解决办法么？要自己去手动记录scrollTop的值？

**Comment by hezhongfeng** [comment]
可以看看我在掘金分享的文章，里面有涉及到
https://juejin.im/user/430664287009646/posts

**Comment by hezhongfeng** [comment]
也可以参考[这个](https://github.com/hezhongfeng/vue-page-stack)

**Comment by xupd** [comment]
好的 谢谢
