### ISSUE TITLE
beforeRouteLeave 调用了两次

### ISSUE THREAD

**Issue by xupd** [hezhongfeng/vue-page-stack#72]
push的话beforeRouteLeave调用了两次，back的话只会一次。

**Comment by hezhongfeng** [comment]
目前找不到解决的办法：
1、没有办法比beforeRouteLeave更早的监测
2、可以通过查询两次钩子的不同参数知道哪个是第一次，比如可以在beforeRouteLeave`console.log(to.query);`，第一次没有stack-key

**Comment by xupd** [comment]
意思是插件处理之前beforeRouteLeave先执行了一次，然后插件处理完，导致beforeRouteLeave又执行了一次？

**Comment by hezhongfeng** [comment]
对的，可以看[这里](https://router.vuejs.org/zh/guide/advanced/navigation-guards.html#%E5%AE%8C%E6%95%B4%E7%9A%84%E5%AF%BC%E8%88%AA%E8%A7%A3%E6%9E%90%E6%B5%81%E7%A8%8B)

**Comment by xupd** [comment]
好的，谢谢大佬。我自己判断一下。
