### ISSUE TITLE
返回了两次，再前进，缓存就没了？

### ISSUE THREAD

**Issue by alphat** [hezhongfeng/vue-page-stack#78]
首页 -> 列表页（进行数据筛选）-> 详情页

从详情页，使用浏览器返回按钮，回到列表页，之前的数据筛选内容还在

然后再使用返回按钮返回到首页（这种情况大多是手误点多了），  **此时，使用浏览器前进按钮，再次回到列表页，数据筛选内容就不在了**

这种情况有办法解决吗？

**Comment by hezhongfeng** [comment]
这不是问题，不需要解决

**Comment by alphat** [comment]
> 这不是问题，不需要解决

如果我想在用户 手误多点了两次返回后，再使用前进按钮进入这个列表时，保留之前的数据，有方法吗？

**Comment by hezhongfeng** [comment]
1、你这是不符合正常的操作逻辑的
2、直接使用KeepAlive
