### ISSUE TITLE
大佬现在碰到一个bug，路由返回的时候添加动画出现异常，会上半截和下半截执行相反的动画，可否建一个讨论群，拍个视频给您看下，文字说不清

### ISSUE THREAD

**Issue by XiaoLizi29** [hezhongfeng/vue-page-stack#81]

**Comment by XiaoLizi29** [comment]
我录了一个视频,,您可以看下：[查看](https://www.weiyun.com/video_preview?videoID=6a390d95-6674-4bb3-aba9-7af3a31fe959&dirKey=5c55e58e9ca75f968600c690bc5e64dc&pdirKey=5c55e58ef0a739ae12b58dcd423dce4a)

**Comment by hezhongfeng** [comment]
先自己处理，对比example

**Comment by hezhongfeng** [comment]
请问，有结果了吗？

**Comment by XiaoLizi29** [comment]
> 请问，有结果了吗？

我用的是vant 的两个动画van-slide-left和van-slide-right,判断是动画包含进入和隐藏两部分,当前页面隐藏的动画和下一个页面出现的动画同时出现的bug,但是即使这样子也不应该是上面视频那种效果，大佬可以把vant这两个动画加上去看下你会不会出现这种情况，链接在下
[链接](https://vant-contrib.gitee.io/vant/#/zh-CN/style)

**Comment by hezhongfeng** [comment]
你可以自行对比example的动画，动画部分是需要你自己搞定的，这个库不处理这些
