### ISSUE TITLE
切换路由会把prop清空,导致在下一个页面报上个页面的错误

### ISSUE THREAD

**Issue by XiaoLizi29** [hezhongfeng/vue-page-stack#83]
比如在a页面,a页面用到了prop中的一个值,然后切换到b页面,这时候会报错,报错信息是在a页面找不到prop的某个值

**Comment by hezhongfeng** [comment]
页面已经是顶级组件了，哪来的prop？

**Comment by XiaoLizi29** [comment]
> 页面已经是顶级组件了，哪来的prop？

顶级组件虽然路由是顶级,但是里面还能分子组件,存在组件传值

**Comment by hezhongfeng** [comment]
好的：
1、可以看看我的example代码，里面也有prop
2、还有疑问可以开个仓库复现这个问题
