### ISSUE TITLE
这个插件调用$router.back()会执行created周期吗

### ISSUE THREAD

**Issue by XiaoLizi29** [hezhongfeng/vue-page-stack#85]

**Comment by XiaoLizi29** [comment]
我发现这个页面返回会执行created周期

**Comment by XiaoLizi29** [comment]
今天早上有测试了下，找出了问题所在，是因为从A页面->B页面的时候，A页面内用了计算属性获取$route的query，而跳到B页面的时候，$route.query的值发生了变化,所以A页面的缓存失效了，目前我使用的hack改为了在A页面的声明周期获取$route.query的值，然后赋值给data，data的值是不会随着路由的变化而更新的，可以实现缓存，不知道还有其他的办法解决这个问题吗？

**Comment by hezhongfeng** [comment]
生命周期和KeepAlive相同，不会执行created，可以自己找找问题所在，另外，不建议『计算属性获取$route的query』

**Comment by XiaoLizi29** [comment]
问题所在就是在计算属性中获取了$route.query,导致计算属性重新计算,缓存失效
