### ISSUE TITLE
如何清除页面栈

### ISSUE THREAD

**Issue by choudewh** [hezhongfeng/vue-page-stack#88]
找了下文档没找到清除页面栈的方法

**Comment by hezhongfeng** [comment]
`let UIStack = this.$pageStack.getStack();`就是获取页面栈的方法，你可以随意的清除和操作

**Comment by choudewh** [comment]
> `let UIStack = this.$pageStack.getStack();`就是获取页面栈的方法，你可以随意的清除和操作

不是清除stack，而是怎么清除组件，因为我发现相同的组件经常出现在组件栈中，我的想的是去监听下路由，回到首页就一次性把所有的组件缓存全部删掉

**Comment by choudewh** [comment]
> `let UIStack = this.$pageStack.getStack();`就是获取页面栈的方法，你可以随意的清除和操作

我发现清除了页面栈，缓存的组件还是存在

**Comment by hezhongfeng** [comment]
没搞懂，你是什么意思～也许你讨论的和`vue-page-stack`没有关系

**Comment by choudewh** [comment]
> 没搞懂，你是什么意思～也许你讨论的和`vue-page-stack`没有关系

简单来说我想在清除页面栈的时候把vnode也销毁掉

**Comment by choudewh** [comment]
解决了，我循环了下页面栈，把每个vnode destroy了
