### ISSUE TITLE
项目中使用了keepalive是否同时使用这个

### ISSUE THREAD

**Issue by pfpGit** [hezhongfeng/vue-page-stack#9]
按文档使用时，报uncought TypeError: Cannot read property  '_leaveCb' of undefined

**Comment by hezhongfeng** [comment]
贴代码，我不知道是怎么同时使用的

**Comment by godo9** [comment]
"vue-page-stack": "^1.5.0",
"vue-router": "^3.2.0",
引入会报同一个错误
