### ISSUE TITLE
replace with an empty stack fails

### ISSUE THREAD

**Issue by foofel** [hezhongfeng/vue-page-stack#91]
if you start an app (and not navigate anywhere) and use `$router.replace("...")` it will throw an invalid vnode error, it happens in line https://github.com/hezhongfeng/vue-page-stack/blob/0425015a1f3d0ba609f8fc434a70357260efba51/src/components/VuePageStack.js#L68 as the stack is empty. I am not sure what the expected behavious is supposed to be but maybe one can assume the initial stack is just the root or do nothing to the previous view if the stack is empty.

**Comment by hezhongfeng** [comment]
thanks for your feedback. I will see it soon.

**Comment by chenjiangui** [comment]
当路由复用时也会因为这句代码造成问题.  replace了同个路由, 但是参数改了, 这句代码强行销毁了实例 导致页面失去响应
