### ISSUE TITLE
如果返回到一个页面的时候重新拉取接口数据，使用back可以返回，但是想重新拉取接口数据有办法吗

### ISSUE THREAD

**Issue by XiaoLizi29** [hezhongfeng/vue-page-stack#94]

**Comment by hezhongfeng** [comment]
有的，参考我的example[代码](https://github.com/hezhongfeng/vue-page-stack-example/blob/0b82ba4e977895def6a17f6b9191d9fa2c087e17/src/views/main/MainList.vue#L32)
