### ISSUE TITLE
Vue3.0 Support

### ISSUE THREAD

**Issue by wozien** [hezhongfeng/vue-page-stack#95]

**Comment by wozien** [comment]
hey gay, When to support Vue3.0?

**Comment by hezhongfeng** [comment]
三个月之内吧，最近太忙了，你们是已经在生产环境使用了Vue3.0全套?

**Comment by wozien** [comment]
> 三个月之内吧，最近太忙了，你们是已经在生产环境使用了Vue3.0全套?

好的，收到 🎉
