### ISSUE TITLE
同一个页面，只修改query，无法watch $route修改，去掉plugin就好了

### ISSUE THREAD

**Issue by defghy** [hezhongfeng/vue-page-stack#96]
rt

**Comment by brightstarlcg** [comment]
> rt

@defghy 这问题现在解决了吧

**Comment by defghy** [comment]
代码不多，我们直接拷贝下来自己改了改
https://github.com/defghy/vue-page-stack

[pr](https://github.com/hezhongfeng/vue-page-stack/pull/104)

**Comment by defghy** [comment]
> > rt
> 
> @defghy 这问题现在解决了吧

代码不多，我们直接拷贝下来自己改了改
https://github.com/defghy/vue-page-stack

[pr](https://github.com/hezhongfeng/vue-page-stack/pull/104)
