### ISSUE TITLE
列表pop进详情页时回把列表滚动的值带入详情？

### ISSUE THREAD

**Issue by ezm-templates** [hezhongfeng/vue-page-stack#97]
您好，我在实践列表pop进详情页时，发现详情页会自动的滚动到某个位置，而不是在最上方

**Comment by hezhongfeng** [comment]
我的example 示例试了吗？
如果example没问题，可u一参考下

**Comment by mjn1154477982** [comment]
![image](https://user-images.githubusercontent.com/20697182/106077979-8d8aec00-614d-11eb-8bc2-bd390cffba9b.png)
可以在页面前进的时候，把滚动条设置到顶部
