### ISSUE TITLE
About Vue3.x

### ISSUE THREAD

**Issue by hezhongfeng** [hezhongfeng/vue-page-stack#99]
年后准备搞Vue3.x的版本，在这里做下记录
目前最大的问题就是新版本的KeepAlive和Vue的核心源码互相杂糅在一起

**Comment by 0x30** [comment]
写了一个自用，可以讨论讨论

https://github.com/0x30/vue-navigation

**Comment by hezhongfeng** [comment]
感谢

**Comment by wcldyx** [comment]
> 写了一个自用，可以讨论讨论
> 
> https://github.com/0x30/vue-navigation

可以使用吗

**Comment by 0x30** [comment]
> > 写了一个自用，可以讨论讨论
> > https://github.com/0x30/vue-navigation
> 
> 可以使用吗

目前我的几个小项目在使用，代码比较简单可以根据自己项目具体开发一下。因为目前版本的 keepalive 不能自由操作，所以干脆复制了一份keepalive代码。但是这样子会造成和官方的 keepalive 的版本不一致，维护之类的问题。可以等待 [pull 3414](https://github.com/vuejs/vue-next/pull/3414)  合并后，使用官方的 keepalive 升级

**Comment by hezhongfeng** [comment]
我也按照你的方法，这么整吧 @0x30
